### ISSUE TITLE
NPCs can stand on water surface

### ISSUE THREAD

**Issue by Dehela** [Try/OpenGothic#322] opened 2022-09-16 11:57 UTC
A bit of Jesus role-playing. Here this guard is angry at me so whenever I try to stand on solid ground, he would attempt to chase me and end up swimming; and he will stand on water if I get to water myself or distance from him.

![1](https://user-images.githubusercontent.com/111627003/190633596-97db0f9b-d91b-4ed2-bce1-9ee2b5f54b76.jpg)

**Comment by Try** [comment] 2022-09-17 22:06
Closing as duplicate of #320  - there is no difference between humans and other living creatures on engine side

**Closed by Try** 2022-09-17 22:06 UTC
