### ISSUE TITLE
Bugfix: Inventory crash when pressing certain buttons

### ISSUE THREAD

**Issue by DHertrich** [Try/OpenGothic#107] opened 2020-12-17 21:27 UTC
Hi,
I just built the project in Windows 10 successfully. The game starts fine but when I try to equip the dagger in front of Xardas' tower, the game crashes seemingly with a segfault.

Info: ZEN: Reading world...
Info: oCWorld reading chunk: MeshAndBsp
Info: ZEN: Reading mesh...
Info: Reading mesh '' (Version: 265)
Info: Found 260696 vertices
Info: ZEN: Done reading mesh!
Info: oCWorld reading chunk: VobTree
Info: oCWorld reading chunk: WayNet
Info: Loading 1 freepoints
Info: Loading 3402 edges
Info: Done loading edges!
Info: Reading 20826 blocks

---crashlog(SIGSEGV)---
GPU: GeForce GTX 970
0x00d6bd8b: CrashLog::dumpStack in C:\Users\Dennis\CLionProjects\OpenGothic\cmake-build-debug\opengothic\Gothic2Notr.exe
0x00d6c04d: signalHandler in C:\Users\Dennis\CLionProjects\OpenGothic\cmake-build-debug\opengothic\Gothic2Notr.exe
0x6d65ef39: seh_filter_exe in C:\WINDOWS\SYSTEM32\ucrtbased.dll
0x00f720ea: __scrt_common_main_seh in C:\Users\Dennis\CLionProjects\OpenGothic\cmake-build-debug\opengothic\Gothic2Notr.exe
0x6d74335e: seh_longjmp_unwind4 in C:\WINDOWS\SYSTEM32\VCRUNTIME140D.dll
0x00f71f1d: __scrt_common_main in C:\Users\Dennis\CLionProjects\OpenGothic\cmake-build-debug\opengothic\Gothic2Notr.exe
0x00f722b8: mainCRTStartup in C:\Users\Dennis\CLionProjects\OpenGothic\cmake-build-debug\opengothic\Gothic2Notr.exe
0x758d6359: BaseThreadInitThunk in C:\WINDOWS\System32\KERNEL32.DLL
0x771d7c24: RtlGetAppContainerNamedObjectPath in C:\WINDOWS\SYSTEM32\ntdll.dll
0x771d7bf4: RtlGetAppContainerNamedObjectPath in C:\WINDOWS\SYSTEM32\ntdll.dll

[save_slot_1.zip](https://github.com/Try/OpenGothic/files/5712236/save_slot_1.zip)

**Comment by Try** [comment] 2020-12-19 11:31
Hi, @DHertrich and thank for bug-report!

I've used your save-file, tryed MSVC-debug, MinGW-debug, MSVC-reldebug, so far no luck in reproducing:
![изображение](https://user-images.githubusercontent.com/122894/102688030-3f043c80-41f4-11eb-957f-e5e377aa4af8.png)

Source revision I've tried: 1ef0541

**Comment by DHertrich** [comment] 2020-12-19 13:34
I'm trying to step thru the code to narrow the error down. So far, I found out, that using left klick works, whereas ctrl crashes the game with segfault.

**Comment by DHertrich** [comment] 2020-12-19 14:40
I think I found the problem. The keydownevent callback was calling the loot logic without checking whether the state is equal to equip. See #108 for a proposed fix.

**Comment by DHertrich** [comment] 2020-12-19 16:24
While taking a closer look, space does the same wich causes it to crash too. The Problem is: I can't see why it would crash when calling onTakeStuff() while in player inventory. When I step through, it crashes at a semi random call to some WINAPI stuff around the msg loop. Maybe the crash happens on another thread because something was invalidated?

**Comment by DHertrich** [comment] 2020-12-21 17:05
I tried to simplify and order the logic a bit. The game would crash when in the inventory menu and pressing loot buttons like ctrl, space among others.

The bug stems from the logic being pretty complex with different combination of states.
I think we should think about splitting the Trade, Ransack and Inventory in three classes inheriting from a page base class, what do you think @Try?

Would this be a welcome enhancement?

**Comment by Try** [comment] 2020-12-29 22:28
As concluded in #108 this crash is actually related to rigid physics, si I've remove it.
BulletDynamics is way to slow anyways and simple 'gravity-only' solver can do for now.

**Comment by Try** [comment] 2020-12-29 22:31
> Would this be a welcome enhancement?

Code cleanup is fine. Creation of 3 new classes is not :) - it will probably make codeeven more complex.

**Comment by Try** [comment] 2021-01-06 22:43
Closing this ticket - assume the issue is fully fixed by 96ce690

**Closed by Try** 2021-01-06 22:43 UTC
