### ISSUE TITLE
Support for Chronicles of Myrtana

### ISSUE THREAD

**Issue by ezamelczyk** [Try/OpenGothic#418] opened 2023-02-28 09:12 UTC
I suppose it is a big ask, but is it possible to implement support for mods such as Chronicles of Myrtana? Right now it doesn't work and when I try to load it with the world option it just spits out `unable to open Zen-file: "ARCHOLOS_MAINLAND.ZEN"`

**Comment by Try** [comment] 2023-02-28 18:28
Chronicles of Myrtana is full DMA mod, so as-is it can't work. There is some sporadic work in #231, with overall plan to override mid-level abstractions. 

Also, even if #231 is completed, CoM also uses external *.dll libraries for steam and music - that won't work at all.

**Comment by Try** [comment] 2023-03-05 19:34
Closing - considering as duplicate of https://github.com/Try/OpenGothic/issues/231

**Closed by Try** 2023-03-05 19:35 UTC
