### ISSUE TITLE
Saves on 2602 and higher doesn't work

### ISSUE THREAD

**Issue by RaHimsky** [Try/OpenGothic#598] opened 2024-03-30 15:57 UTC
Hi,

some time ago I started playing in Gothic II NOTR on OpenGothic 2207. Everything is good to 2601 version. When I'm trying 2602 or higher version I have problem with some my saves. They just don't want loading. I play on clear version of G2NOTR only with Panker Mod Mix but I tried loading my saves without this texture pack and they don't work too.

Here's my saves https://mega.nz/file/d1pCASaB#JMDB23FVH6fUd3dbYqESTlJ1OghaBH9NEMzirP9JDn8

The saves number 8 and 14 working correct problem is with saves number 15-18.

**Comment by Try** [comment] 2024-03-30 21:06
HI, @RaHimsky !

I've tested save `8` and `15`. 15 has invalid version tag, possible there was series of commits around build 2602, with this bug. 
Root cause of the issue is fixed in latest build: loading `8` and saving it again produces a valid save-game file

**Comment by RaHimsky** [comment] 2024-03-30 22:13
Thanks for reply, so I need to start my game from save 8/14 or my later saves will be working on next build? Sorry, but I don't fully understand. Is there any way to change the version tag manually to make the saves 15-18 working on 2602+ builds?

**Comment by Try** [comment] 2024-03-31 00:14
> Thanks for reply, so I need to start my game from save 8/14 or my later saves will be working on next build? 

on *current build, yes

> Is there any way to change the version tag manually to make the saves 15-18 working on 2602+ builds?

No easy/reliable one. If you really keen on this - you can open save-game as .zip archive with 7zip or winrar. There you will find `save_slot_18.sav/worlds/newworld.zen/version` file. This is a 2 byte binary file with a version number, you need a hex-editor to edit such, or transfer it from other save (with v46). Save for every game world.

**Comment by RaHimsky** [comment] 2024-03-31 15:23
Ok, I fixed my save number 18 but it's work only for newworld.zen and I tested it on 2628 build. When I do the same for oldworld.zen version file or addonworld.zen the game still don't want load save even if my character is in newworld.zen. And what I noticed, when I saved the game after editing version file for newworld.zen the values changed from 46 to 48.

**Closed** 2024-04-03 22:13 UTC
