### ISSUE TITLE
It's Christmas in Khorinis

### ISSUE THREAD

**Issue by hwnde** [Try/OpenGothic#578] opened 2024-02-14 07:17 UTC
Trees have weird colored pixels which kinda look like Christmas lights from distance.

Windows 11, commit 26b816e36d05832f90851d2924209f14e6d88050
GPU: amd 6800 xt, meshlets off
![Screenshot 2024-02-13 225819](https://github.com/Try/OpenGothic/assets/6673733/b9a97d89-08a0-40b3-b54c-495ceb35fb75)

**Comment by Try** [comment] 2024-02-14 19:31
HI, @hwnde and thanks for report!

Can you please provide more information about nature of artifact: 
* is it persistent, or broken pixels are different every frame?
* only trees (aka alpha-tested materials) are affected, or other materials as well?

Can you please test it with `-bl 0` and check if issue is reproducible?

**Comment by thokkat** [comment] 2024-02-14 20:20
Have other case:
![Screenshot_20240214_205630](https://github.com/Try/OpenGothic/assets/100468436/5a007780-6413-4b96-865b-194ad15b3389)

>   is it persistent, or broken pixels are different every frame?

It looks like raining or snowing for ~15s with torch as source. Then it looked normal. After a teleport to harbor and F8 flying back it started anew.

>  only trees (aka alpha-tested materials) are affected, or other materials as well?

Trees are ok here. Found this behavior only at tavern torch, e.g. brothel torch is ok.

> Can you please test it with `-bl 0` and check if issue is reproducible?

Same as `-bl 1`.

**Comment by Try** [comment] 2024-02-14 22:09
@thokkat you talking about particle-effect, yet this is not how screen-shoot on topic looks like.

Notice, that there is mostly single pixels artifacts, and color are somewhat random. Imao, it looks a lot like warp/quad divergence bug. Also divergence explains, why issue is not observable on NVidia/Apple/Intel - they have HW support for variable indexing and do not care about shader code.

**Comment by hwnde** [comment] 2024-02-15 05:18
@Try  `-bl 0` doesn't solve the issue

The broken pixels are persistent as long as I don't move the camera.
It seems like this is present on any vegetation, i.e. leaves on water. Interestingly it seems to disappear if I view the texture up close.

**Comment by Try** [comment] 2024-02-17 22:48
marking it as help-wanted: I'm not familiar with such type of graphical artifacts.
Normally, when it application bug, pixels(and draw-order) is not persistent, yet it's unlikely that AMD didn't manage to implement texturing.

**Comment by Try** [comment] 2024-02-18 19:22
I've put some changes to pre-pass stage in [a4b98a7](https://github.com/Try/OpenGothic/commit/a4b98a75431ea14c965879e0ba1a1e29fac8d66f)

@hwnde I can't confirm it locally, please test it on you side, if you have time. Thanks!

**Comment by hwnde** [comment] 2024-02-19 03:43
@Try It worked! The issue disappeared!

**Closed** 2024-02-19 17:23 UTC
Labels: help wanted
