### ISSUE TITLE
Problems you can easily reproduce in Expansion world's swamp, one in Jharkendar / Khorinis, one at the pub when joining the ring of water etc.

### ISSUE THREAD

**Issue by dreimer1986** [Try/OpenGothic#246] opened 2022-02-06 22:30 UTC
I am in a lil test playthrough right now. Some things are a bit funny till now and I thought you might wanna hear of them.

First I already witnessed quite some times that NPCs are just lying around dead or are falling off high points trying to get back up again. Our good friend Valentino for example. I have no clue how he died though. I found him in his house, dead. I fixed that and later he was lying on the entrance of the pub in the city. Next to the entrance not pointing to the Adanos temple. There is a bench:

![image](https://user-images.githubusercontent.com/29841368/152704337-fe0469df-996b-4e3a-b3d9-d1ff48c19c05.png)

Here he was lying quit dead. Later I saw another NPC hopping around on that bench and out of luck he did hurt himself quite a bit again and again. Sadly I did not make a video of that...

Next one is the meeting of the ring of water. In the end the meeting was me, Lares, Orlan and whoever stands in the corner right to the entrance under the balcony. The rest was not showing up. When I left the pub I saw Cavalorn leaving. He never managed to get to the meeting though. Rest was missing completely.

Next the swamp:

![image](https://user-images.githubusercontent.com/29841368/152704398-a0febbe6-2b57-495b-84fa-188203a7e905.png)

Just try to walk over the bridge and witness that you will get stuck quite likely, You have to climb some parts. This problem happens on other parts, too, but here it was the most obvious. (Maybe the portal to Jharkendar portal in the Khorinis map is another example to look at)

Next our poor Saturas:

![image](https://user-images.githubusercontent.com/29841368/152704372-26c4178b-6044-49d2-8312-61b90d053d92.png)

Talking about people loving to fall off cliffs, he fell down there and now tries to get back by hopping again and again.

Gregs bloody crosses sometimes eat up your pickaxe and you need a new one. No clue if that is a bug in the original too.

Is it possible that sleeping mobs and NPS are not waking up when I am too loud? Stealing of the high society's houses seems to be a bit too easy and Schattenäufer https://www.worldofgothic.de/images/content/gothic2/monster/schattenlaeufer.jpg are not waking up at all.

I am quite sure that I already forgot some minor things, but these are left in my memories.

Some of these can be found a lil different in Gothic I, too. But as this is not the aim right now, I keep these for later.

And as lil off topic. Did you try The Chronicles of Myrtana Archolos already? It does not load a new game. Neither this is your aim, just wanted to let you know.

**Comment by Try** [comment] 2022-02-07 21:37
Hi, @dreimer1986 and thanks for report!

> Here he was lying quit dead. Later I saw another NPC hopping around on that bench and out of luck he did hurt himself quite a bit again and again.

Hard to say what exactly happen to him, for now let's assume that this is variation of #234 bug.

> Next one is the meeting of the ring of water.

This meeting issue is scrips related: game sends all npc's to walk manually to meeting, rest is depends on processing distance.
In vanilla game processing is limited to ~20-30 meters, so Lares, Covalord and other will teleport to near the tavern and then walk in. However, in OpenGothic walk, meas they will walk for real, from city and farm.
Most simple way to avoid this is to take a sleep in tavern, so everyone can arrive.

> Just try to walk over the bridge and witness that you will get stuck quite likely

Aware: in game there is a `step_height` value provided by script - maximum step up delta height.
It can be that vanilla and OpenGothic disagree on how to evaluate this delta - need to check same area in vanilla.

> Gregs bloody crosses sometimes eat up your pickaxe and you need a new one. 

That's my bug - started separated #248  ticket for that.
 
> poor Saturas

I'll check, might be already fixed in  #234

> Is it possible that sleeping mobs and NPS are not waking up when I am too loud?

Should wake up, unless you shave sneaking skill active - I'll check.

**Comment by dreimer1986** [comment] 2022-02-08 12:02
Well, I have the sneak skill, but rattled and crushed in the cave without it in walk/run mode. I walked around the mod three times,. still asleep. Same for the chest owners in the high society houses of Khorinis.

Btw, THANKS for making that project :D

**Comment by Try** [comment] 2022-02-08 17:30
> And as lil off topic. Did you try The Chronicles of Myrtana Archolos already? It does not load a new game. Neither this is your aim, just wanted to let you know.

Yes, I've tried. Since this mod is non-conformant that will require #231 to be implemented - that's quite a lot of work.
Forgot to answer to this :)

**Comment by dreimer1986** [comment] 2022-02-08 23:52
Almost expected that. Thanks for the clarification. ^^

**Comment by dreimer1986** [comment] 2022-02-10 14:45
Will test his one ASAP. But I have another one for you.

I use the keyboard only GI controls and it seems like for example looting a killed mob changes the viewing angle of the hero. I often have to adjust is with mouse.

**Comment by Try** [comment] 2022-02-14 22:12
> looting a killed mob changes the viewing angle of the hero
This behavior matches vanilla game:
every time camera instance changes, for example from `CamModNormal` to `CamModInventory`, engine must reset camera angles

**Comment by dreimer1986** [comment] 2022-02-25 23:11
I have a few more:
- When telling Esteban about FIsk in the pub, his guards never manage to come close to the pub, they die very close to Esteban.
- I bought a new armor from Huno, dressed with it and hell was freezing over. Everyone attacked me.
- Something with these pickaxes is funny... I upped Gold mining to 100% and no Gold ore on the wall can be mined. No animation and one pickaxe less with every try.
- Thorus seemed to have forgotten that I killed Bloodwyn, he spoke to me twice about the same thing. Second time after I saw Raven going inside the temple.
- Merdarion does not hand me any Focus anymore. No clue why and since when. Went on when I was cheating another in my hands. THen I was able to finish the last two ones.
- The repel from some plants and trees is... quite a bit too much? Sometimes you feel like a Pinball in deeper vegetation.
- Traps in the Adanos Temple don't hurt.
- Rhademes does not pull a trigger as exprected, he jumps on a wall instead.
This is the end of the expansion then. Rest works as it seems.

**Comment by Try** [comment] 2022-07-10 20:03
Fixed in 1.0.1527:
> Next our poor Saturas:
> Gregs bloody crosses sometimes eat up your pickaxe and you need a new one
Fully fixed

> Here(Bartok) he was lying quit dead

Generally fixed, or at least not reproducible anymore. Yet there is an echo of this path-find issue: when npc collides with something it will bounce + when npc collides with door, it will call script callback to open the door. Abuin open hotel door to thieves guild by accident, in my play-thru :/ 

> Merdarion does not hand me any Focus anymore.

Not reproducible atm

> Traps in the Adanos Temple don't hurt.

Reproduced, still need to fix this.

Other stuff is still need to be tested - not yet there in a game

**Comment by dreimer1986** [comment] 2022-07-11 14:12
Next play around will come soon. Will check for the likely fixed ones then. :D

**Comment by Try** [comment] 2023-07-23 11:06
> Beliar's Claw does not have the nice black smoke around it.

Decouple it into: https://github.com/Try/OpenGothic/issues/494

Rest seem to be fixed, but feel free to submit new issues, if I miss something

**Closed by Try** 2023-07-23 11:06 UTC
