### ISSUE TITLE
Increase font size  and size of UI elements in the game. MacOS m1.

### ISSUE THREAD

**Issue by lectricas** [Try/OpenGothic#534] opened 2023-11-13 19:53 UTC
Is there a setting for that? Can't read! 
<img width="1280" alt="Screenshot 2023-11-13 at 20 49 01" src="https://github.com/Try/OpenGothic/assets/8782219/a9cfa71f-057f-4a60-aade-5f7d0a53600e">
<img width="1280" alt="Screenshot 2023-11-13 at 22 52 05" src="https://github.com/Try/OpenGothic/assets/8782219/9bfb9ee1-3e2e-47af-84ba-c9a02037de0c">
<img width="1280" alt="Screenshot 2023-11-13 at 22 52 25" src="https://github.com/Try/OpenGothic/assets/8782219/c18c1550-da01-403b-9dc4-5dd32fd9eb94">

**Comment by Try** [comment] 2023-11-13 23:46
We are missing `INTERFACE/scale` flag from systempack at this moment - need to implement.

Closing this ticket as duplicate of: https://github.com/Try/OpenGothic/issues/301#issuecomment-1808958606

**Closed by Try** 2023-11-13 23:46 UTC
