### ISSUE TITLE
Earthquake can be heard from large distance

### ISSUE THREAD

**Issue by Dehela** [Try/OpenGothic#305] opened 2022-09-13 09:38 UTC
Looks like there is an issue with earthquake, which happens near temple ruins which leads to Jharkendar, that it can be heard from large (or even unlimited) distance. Like, starting the game in Xardas Tower, you can already hear it from time to time.

I suppose it might something to do with full life simulation (like mentioned in FPS ticket) for this version so the event happens despite the distance. It case if it matters, I was testing master branch on Linux.

**Comment by Try** [comment] 2022-09-14 20:53
> I suppose it might something to do with full life simulation

Almost: actual root cause of earthquakes in game is Saturas. In his state-script he has 5% chance to summon global earth-quake.

Script callstack:
```
"WLD_PLAYEFFECT"
"B_EVENT_PORTAL_EARTHQUAKE"
"ZS_STUDY_WP_LOOP"
--- 
Npc::tickRoutine
```

**Comment by Dehela** [comment] 2022-09-14 21:07
So, is it actually a normal thing to happen? I haven't play the game for quite a while so I might recall things wrong.

**Comment by Try** [comment] 2022-09-14 21:33
I'm also not 100% sure how it was in vanilla.

So far my point is:
1. Earthquakes are related to npc-processing
2. It' likely that original game doesn't execute npc-state-scripts, if npc is outside of certain distance 
3. Script is crap to begin with :)

**Comment by Dehela** [comment] 2022-09-15 07:37
Sounds like a complicated issue to fix unless things are altered. Probably excluding world effect from that script is the least evil, which is unfortunate if you aim to keep game logic intact as it was in original (but might be not too bad if it's not the first time to make a workaround patch).

**Comment by PolyMeilex** [comment] 2022-09-17 15:19
Random idea, perhaps we could check source of the effect and fade it smoothly based on position, so instead of unloading like gothic did it woul be a lot nicer and slowly decay over distance.

**Comment by sirsteve1** [comment] 2022-10-27 06:26
> > I suppose it might something to do with full life simulation
> 
> Almost: actual root cause of earthquakes in game is Saturas. In his state-script he has 5% chance to summon global earth-quake.
> 
> Script callstack:
> 
> ```
> "WLD_PLAYEFFECT"
> "B_EVENT_PORTAL_EARTHQUAKE"
> "ZS_STUDY_WP_LOOP"
> --- 
> Npc::tickRoutine
> ```

Dear __Try__, I tried to find the callstack of the earthquake routine but had no chance of finding anything. In which files would I have to lookup? I would like to play around and see if I can find a solution for this. Checked out both the OpenGothic repo as well as the Gothic2 game folder but found nothing...

**Comment by Try** [comment] 2022-10-28 07:49
Hi, @sirsteve1 !

`Npc::tickRoutine` - npc.cpp
`WLD_PLAYEFFECT` - gamescript.cpp (GameScript::wld_playeffect)
`B_EVENT_PORTAL_EARTHQUAKE`- script_g2\Content\Story\Events\B_Event_Portal_EarthQuake.d (not in opengothic repo - you need original game scripth here)
`ZS_STUDY_WP_LOOP` - script_g2\Content\AI\Human\TA_Human\ZS_Study_WP.d

**Comment by Try** [comment] 2024-07-17 21:36
Looking at this as well in to https://github.com/Try/OpenGothic/pull/653, I think we need to summarize cases first and agree on how to address problem overall and not particular cases.

So the issue: full world simulation results in significant behavior differences between OpenGothic and Gothc2.

#### Why full world simulation:
* Goes very well along limitless view distance, resulting in better game experience 
* Gives us a reason to say that npc runtime doesn't degradate over time (good for testing)
* and just cool overall :)

#### Known issues
* Earthquake (this issue)
  * Essentially any other global call from script, akin to `WLD_PLAYEFFECT` will cause trouble
* https://github.com/Try/OpenGothic/issues/585
  * Ring of water meeting(Lares and others travel in real-time)
  * Greg doesn't come quick enough to kill Dexter
* https://github.com/Try/OpenGothic/issues/354
  * NPCs won't heal in time
* Npc state doesn't refresh(part of https://github.com/Try/OpenGothic/pull/653)
* Maybe more? 

> Perhaps we could not execute routines of NPCs that have Npc::ProcessPolicy::AiFar or at least Npc::ProcessPolicy::AiFar2 set?

At least `aiState.funcIni` has to be invoked in order for npc to progress and walk to next point in theirs time-table. I'm assuming in vanilla, if npc is away, from player engine will move it automatically. Also need to handle auto move/teleport for `Npc_ExchangeRoutine`.
So not calling `aiState` and handle npc movement in engine manually is an option: fixing many issues, except #585 . For #585 need something more advanced.

One thing to note here, I wish orks outside the castle not to stand in idle pose, but be more organic. This requires to invoke `aiState.funcIni` at least once for all npc's, what unfortunately doesn't go along with proposed scheduling, but it's ok.

**Comment by thokkat** [comment] 2024-07-18 22:28
>     * Earthquake (this issue)
>       
>       * Essentially any other global call from script, akin to `WLD_PLAYEFFECT` will cause trouble

Maybe don't execute commands which produce a sound or effect that can confuse the player. Like it's done for svm-talks and keep gloabal script.

>     * NPC problems
>       
>       * NPCs won't heal in time
> 
>     * Npc state doesn't refresh

Motivation for pr was that templars in sleeper temple missing equip command in script. Testing showed that best weapons are equipped every time npc comes in visibility range. At same time script is called to restore health.

I think handling these two in `Npc::resetPositionToTA` which covers sleep and world change missing only the "npc is now visible" call makes most sense. 

>     * Maybe more?

Not more but cases where workarounds/hacks are already in place.

Pedro removal in`Npc::startState`, same as Greg/Dexter.
```C++
  if(wp=="TOT" && aiPolicy!=Player && aiPolicy!=AiNormal) {
    // workaround for Pedro removal script
    auto& point = owner.deadPoint();
    attachToPoint(nullptr);
    setPosition(point.position());
    }
```

No call to state loop for far away monsters in `Npc::tickRoutine`

```C++
  /*HACK: don't process far away Npc*/
  if(aiPolicy==Npc::ProcessPolicy::AiFar2 && routines.size()==0)
    return;
```

**Comment by Try** [comment] 2024-07-24 22:55
Closing in favor of https://github.com/Try/OpenGothic/issues/657

**Closed** 2024-07-24 22:55 UTC
