### ISSUE TITLE
Camera resets to a weird position everytime when picking up items or looting

### ISSUE THREAD

**Issue by progward** [Try/OpenGothic#104] opened 2020-12-06 19:52 UTC

**Comment by Nindaleth** [comment] 2021-01-28 20:30
Is there a reproduction (specific problematic item) we could try? I've tried picking up some items in and around Xardas' tower and the only time where I can see the camera reset visibly is when "closing the book" on the bookstand.

**Comment by Try** [comment] 2021-07-29 21:34
Closing as duplicate of #161

**Closed by Try** 2021-07-29 21:34 UTC
